### ISSUE TITLE
Appropriate attribution to WonderCMS - MIT license requirements

### ISSUE THREAD

**Issue by robiso** [BoidCMS/BoidCMS#11]
Hello @shoaiyb

First of all, good work on forking and heavily modifying WonderCMS, this project looks pretty good.

However we're sad to see there is zero attribution (or we failed to find it) for WonderCMS, **which is released under the MIT license**.

After a code review and going through your app, we still notice some exact code and functionality copied directly from WonderCMS. At some places it's fairly obvious, on some parts some minor or major changes were made.

----
Forking an MIT licensed project includes:
Include Copyright 
- You must include the copyright notice in all copies or substantial uses of the work.
Include License 
- You must include the license notice in all copies or substantial uses of the work.

Additionally
> Someone can't make a "GPL fork" of a MIT-licensed project. The new code they add can be GPL-licensed, but they cannot simply change the licensing of the existing code from MIT to GPL. The text of the original MIT license must be intact.
----

How to resolve this:
1. Adding "Fork of WonderCMS" in your index.php file in the comment Iwhere it originally stated the license, WonderCMS name and website)-> https://github.com/BoidCMS/BoidCMS/blob/master/index.php
2. Retaining the original MIT license and attributions in the readme file.

Opened this discussion also on your discussions board: https://github.com/BoidCMS/BoidCMS/discussions/12

Edit: After further discussion with the team, we agreed to provide a simple example

WonderCMS code:
```
  /**
   * Get CSRF token
   * @return string
   * @throws Exception
   */
  public function getToken(): string
  {
    return $_SESSION['token'] ?? $_SESSION['token'] = bin2hex(random_bytes(32));
 }
```

BoidCMS code:
```
  /**
   * CSRF token
   * @return string
   */
  public function token(): string {
    return ( $_SESSION[ 'token' ] ?? $_SESSION[ 'token' ] = bin2hex( random_bytes(32) ) );
  }
```

We love forks and open source projects and we'd love to resolve this and give you a friendly mention for an awesome fork on our Twitter. Supporting and attributing each other is a big point in the open source community.

**Comment by BoidCMS** [comment]
See https://github.com/BoidCMS/BoidCMS/discussions/12

**Comment by robiso** [comment]
@BoidCMS @shoaiyb would you be so kind to leave this issue opened for the open source community to decide on their own?

-- Pasting full response from #12 


@BoidCMS thank you for the response, however as mentioned there seem to be more similarities as mentioned previously.

While flat file CMSes share a lot of things in common, we'd ask you to review the things are are indeed to similar and identical, both code and logic wise.

We're prefacing this post of the examples below starting with this article, where BoidCMS is explained to offer things that WonderCMS hasn't:
- https://dev.to/shoaiyb/boidcms-a-simple-fast-and-super-extensible-cms-8gg

Additional examples follow below.

## Example 1 (readme vs readme and about me)
- WonderCMS description
> It's installed without any configuration, since no relational database (like MySQL) is required.
- BoidCMS description from the commit history (exact copy paste)
> It's installed without any configuration, since no relational database (like MySQL) is required.
> https://github.com/BoidCMS/BoidCMS/commit/eb49deed1be0f24e766c54f264a45a74e259b951
- You'll also find the exact same heading titles as well in the commit.
3. Short history Who, why? (taken from WonderCMS about page)
- Similarly, from the BoidCMS readme above.

## Example 2
- Almost identical database structure (with BoidCMS having more fields)

```
// WonderCMS database.js
{
    "config": {
        "siteTitle": "Website title",
        "theme": "default",
        "defaultPage": "home",
        "login": "loginURL",
        "loggedIn": false,
        "forceLogout": false,
        "password": "$2y$10$Lg9eLfREO.L2XuLmNRPYk.Yot.h080QDwyx48dvMUXqFdCyVg5NZ6",
        "lastLogins": {},
        "defaultRepos": {
            "themes": {},
            "plugins": {},
            "lastSync": null
        },
        "customRepos": {
            "themes": {},
            "plugins": {}
        },
        "menuItems": {
            "0": {
                "name": "Home",
                "slug": "home",
                "visibility": "show"
            },
            "1": {
                "name": "Example",
                "slug": "example",
                "visibility": "show"
            }
        }
    },
    "pages": {
        "404": {
            "title": "404",
            "keywords": "404",
            "description": "404",
            "content": "<h1>Sorry, page not found. :(<\/h1>"
        },
        "home": {
            "title": "Home",
            "keywords": "Keywords, are, good, for, search, engines",
            "description": "A short description is also good.",
            "content": "<h1>Website alive!<\/h1>\n\n<h4><a href=\"https:\/\/www.wondercms.com\/devPrepare\/wcms304\/wondercms\/loginURL\">Click to login.<\/a> Your password is: <b>Xj4v67CI<\/b><\/a><\/h4>"
        },
        "example": {
            "title": "Example",
            "keywords": "Keywords, are, good, for, search, engines",
            "description": "A short description is also good.",
            "content": "<h1>How to create new pages<\/h1>\n<p><i>Settings -> General -> Add page<\/i><\/p>\n\n<h1>How to edit anything<\/h1>\n<p>Click anywhere inside the gray dashed area to edit. Click outside the area to save.<\/p>\n\n<h1>How to install\/update themes and plugins<\/h1>\n<p>By opening the Settings panel, you can install or update themes and plugins.<\/p>"
        }
    },
    "blocks": {
        "subside": {
            "content": "<h3>About your website<\/h3>\n\n<p>Website description, photo, contact information, mini map or anything else.<\/p>\n<p>This blue editable area is visible on all pages.<\/p>"
        },
        "footer": {
            "content": "&copy;2020 Your website"
        }
    }
}
```


```
// BoidCMS database.json
{
    "site": {
        "lang": "en",
        "title": "BoidCMS",
        "keywords": "BoidCMS, Keywords, for, seo",
        "subtitle": "Simple, fast, super extensible.",
        "descr": "Simple, fast, super extensible CMS to build simple websites at ease.",
        "url": "http:\/\/example.com\/",
        "email": "mail@example.com",
        "username": "admin",
        "password": "$2y$10$...",
        "footer": "Copyright &copy; 2022",
        "theme": "visual",
        "admin": "admin"
    },
    "pages": {
        "404": {
            "type": "page",
            "title": "Not Found",
            "descr": "404 Page Not Found",
            "keywords": "404",
            "content": "<p>It looks like nothing was found at this location.<\/p>",
            "thumb": "",
            "date": "",
            "pub": true
        },
        "hello-world": {
            "type": "post",
            "title": "Welcome to BoidCMS!",
            "descr": "Welcome to your new website",
            "keywords": "BoidCMS, Keywords, for, seo",
            "content": "<h1>Welcome to BoidCMS!<\/h1><p>This is a sample post, login now to edit or delete it.<\/p><p>Have fun! :)<\/p>",
            "thumb": "",
            "date": "2022-07-26T07:58:28",
            "pub": true
        }
    },
    "installed": {}
}
```

## Example 3
Comparing WonderCMS index.php and BoidCMS unset actions:
`unset($_SESSION['loggedIn'], $_SESSION['rootDir'], $_SESSION['token'], $_SESSION['alert']);`
`unset( $_SESSION[ 'logged_in' ], $_SESSION[ 'root' ], $_SESSION[ 'token' ], $_SESSION[ 'alerts' ] );`
Similarly, you'll find a very similar alert function (our original name was alerts)

## Example 4
Comparing the save function
- wcms: https://github.com/robiso/wondercms/blob/4b203539a566250ac0080a0cba65cf47bd5225d7/index.php#L2041
- bcms: https://github.com/BoidCMS/BoidCMS/blob/master/app/app.php#L205

## Example 5
- Same logic for creating data/plugings/themes and generating database.json file upon installation.

## Example 6
- Nearly identical .htaccess file (except for the last line) and p being renamed to page.
wcms
```
Options -Indexes
ServerSignature Off
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.+)$ index.php?page=$1 [QSA,L]
RewriteRule database.js - [F]
RewriteRule cache.json - [F]
```

bcms
```
Options -Indexes
ServerSignature Off
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.+)$ index.php?p=$1 [QSA,L]
RewriteRule ^(app|data)/.*$ - [R=404,L]
```

## Example 7
Using our hacked way of URL's which is pretty unique and has been critizised in the past (the pull code can be found in both of our repositories)
(( $_SERVER[ 'SERVER_PORT' ] == '80' ) || ( $_SERVER[ 'SERVER_PORT' ] == '443' ) ) ? '' : ':' . $_SERVER[ 'SERVER_PORT' ] )
(($_SERVER['SERVER_PORT'] == '80') || ($_SERVER['SERVER_PORT'] == '443')) ? '' : ':' . $_SERVER['SERVER_PORT'])

## Example 8
- Exact text copy/pasts like some of our errors:
>     $msg = 'Failed to move uploaded file';
> 	$this->alert('danger', 'Failed to move uploaded file.');

## Example 9
Exact same order and nearly identical code for handling uploading files

wcms
```
			case UPLOAD_ERR_OK:
				break;
			case UPLOAD_ERR_NO_FILE:
				$this->alert('danger',
					'No file selected. <a data-toggle="wcms-modal" href="#settingsModal" data-target-tab="#files"><b>Re-open file options</b></a>');
				$this->redirect();
				break;
			case UPLOAD_ERR_INI_SIZE:
			case UPLOAD_ERR_FORM_SIZE:
				$this->alert('danger',
					'File too large. Change maximum upload size limit or contact your host. <a data-toggle="wcms-modal" href="#settingsModal" data-target-tab="#files"><b>Re-open file options</b></a>');
				$this->redirect();
				break;
			default:
				$this->alert('danger', 'Unknown error.');
				$this->redirect();
```

bcms
```
      case UPLOAD_ERR_OK:
        break;
      case UPLOAD_ERR_NO_FILE:
        $msg = 'No file has been sent';
        return false;
        break;
      case UPLOAD_ERR_INI_SIZE:
      case UPLOAD_ERR_FORM_SIZE:
        $msg = 'File too large';
        return false;
        break;
      default:
        $msg = 'An unexpected error occurred';
        return false;
        break;
    }
```

## Example 10 (taken from older version of WonderCMS)
Using theme selector within settings function
```
		foreach (glob(__DIR__ . '/themes/*', GLOB_ONLYDIR) as $dir) {
			$output .= '<option value="' . basename($dir) . '"' . (basename($dir) == wCMS::get('config', 'theme') ? ' selected' : '') . '>' . basename($dir) . ' theme' . '</option>';
		}
```

```
          foreach ( $this->themes as $theme ) {
            $layout[ 'content' ] .= '<option value="' . $theme . '"' . ( $this->get( 'theme' ) === $theme ? ' selected' : '' ) . '>' . ucwords( str_replace( '-', ' ', $theme ) ) . '</option>';
          }
```

## Example 11
- Loggedin defined within "gods" class and just renamed
isset($_SESSION['loggedIn'], $_SESSION['rootDir']) && $_SESSION['rootDir'] === $this->rootDir;
isset( $_SESSION[ 'logged_in' ], $_SESSION[ 'root' ] ) ? $this->root === $_SESSION[ 'root' ] : false );


# Conclusion
There are numerous other similarities (or modified copies) of our code including a replica bug which was present on an older version of WonderCMS, which is pretty evident.

The exact copies of certain things (or slightly modified) are extremely unlikely to happen within two projects of the same kind. We're going to leave the opinion of this discussion to the open source community.

Thanks for your response and kind regards.

**Comment by robiso** [comment]
@BoidCMS @shoaiyb 

@BoidCMS changed reviewed and approved on the private repository.
As soon as this is merged we're closing this issue and becoming your official fans and supporters via a Twitter post!

**Comment by shoaiyb** [comment]
Changes have been merged.

**Comment by robiso** [comment]
@BoidCMS @shoaiyb we're preparing a Twitter post in order to support you.

- Do you possibly have a Twitter handle?
- Should we link to https://boidcms.github.io/ or is there any other URL you would prefer?
