### ISSUE TITLE
Using JSON as a database is  a big security risk

### ISSUE THREAD

**Issue by 1337kid** [BoidCMS/BoidCMS#25]
An attacker can get the password hash by viewing web-url/data/database.json. I would suggest keeping the hash hidden somewhere

**Comment by shoaiyb** [comment]
Hello @1337kid, and welcome to the community.

First of all, BoidCMS was built with security in mind. Regarding your concern, there is a documentation page that explains it: [https://boidcms.github.io/#/folder?id=data](https://boidcms.github.io/#/folder?id=data).

The `data/` folder, where the database is stored, is **protected by default** using the Apache [`.htaccess`](https://github.com/BoidCMS/BoidCMS/blob/master/.htaccess) file. No file in that folder can ever be viewed via a URL.

As for the password, let's imagine it has been leaked. It was hashed using the most recommended one-way password hashing method in PHP, specifically the [`password_hash`](https://www.php.net/manual/en/function.password-hash.php) function. Decoding such a hash is almost impossible.

**Comment by shoaiyb** [comment]
Hello @1337kid, and welcome to the community.

First of all, BoidCMS was built with security in mind. Regarding your concern, there is a documentation page that explains it: [https://boidcms.github.io/#/folder?id=data](https://boidcms.github.io/#/folder?id=data).

The `data/` folder, where the database is stored, is **protected by default** using the Apache [`.htaccess`](https://github.com/BoidCMS/BoidCMS/blob/master/.htaccess) file. No file in that folder can ever be viewed via a URL.

As for the password, let's imagine it has been leaked. It was hashed using the most recommended one-way password hashing method in PHP, specifically the [`password_hash`](https://www.php.net/manual/en/function.password-hash.php) function. Decoding such a hash is almost impossible.

**Comment by 1337kid** [comment]
Interesting... I tried the web app with php web server. So it was visible for me. My bad

**Comment by xiamuguizhi** [comment]
> 你好@1337kid，欢迎加入社区。
> 
> 首先，BoidCMS 在构建时就考虑到了安全性。关于您的担忧，有一个文档页面对此进行了解释：[https://boidcms.github.io/#/folder](https://boidcms.github.io/#/folder?id=data) ?id=data 。
> 
> `data/`存储数据库的文件夹默认使用 Apache 文件进行保护**。**该[`.htaccess`](https://github.com/BoidCMS/BoidCMS/blob/master/.htaccess)文件夹中的任何文件都无法通过 URL 查看。 尝试`curl "https://boidcms.alwaysdata.net/data/database.json"`
> 
> 至于密码，我们假设它已被泄露。它是使用 PHP 中最推荐的单向密码哈希方法（特别是函数）进行哈希处理的[`password_hash`](https://www.php.net/manual/en/function.password-hash.php)。解码这样的哈希几乎是不可能的。

```bash
server {
    # The port on which the server listens for incoming requests. In this case, it's port 80.
    listen 80;

    # The domain name for which this server configuration is applicable. Replace 'your_domain_name' with the actual domain.
    server_name your_domain_name; 

    location /data {  # This section configures the handling of requests for the '/data' path
        # Specifies the actual path of the folder on the server. Replace '/var/www/mysite/data' with the correct folder path.
        alias /var/www/mysite/data; 

        # If the requested file or directory doesn't exist, it returns a 404 error.
        try_files $uri $uri/ =404;

        # Turns off directory listing, preventing the display of the file list within the folder.
        autoindex off; 
    }
}
```
