### ISSUE TITLE
No admin page

### ISSUE THREAD

**Issue by ventoux84** [BoidCMS/BoidCMS#29]
Hello, i would like to test BoidCMS, but I start by encountering a difficulty.
The documentations says :
Visit the [admin panel](https://www.my_domain/boid/admin) and login if not already, then Navigate to Update, select Home (home) and click Select, Update the fields you want to change and click Update to save the changes.

But the link fails and there is no directory or page called admin in the zip downloaded.

**Comment by shoaiyb** [comment]
Hello @ventoux84, it is best to follow the [installation instructions](https://boidcms.github.io/#/install) from the documentation site to avoid any confusion.

Also note that BoidCMS uses Apache `mod_rewrite` to route and to handle requests, and that the **admin panel is dynamically created** so you won't find any directory or file named `admin`. So you should check for the `.htaccess` file in the root and see if it was missing.


But if you are testing it on a PHP Built-In development server then you have to roll your own router or go for the [`index.php` modification](https://boidcms.github.io/#/install?id=run-boidcms-with-php-built-in-web-server) for it to work.
