### ISSUE TITLE
Stored XSS vulnerability in "Create" & "Update" section of admin panel

### ISSUE THREAD

**Issue by 1337kid** [BoidCMS/BoidCMS#31]
Due to improper input validation, it's possible to create a page/post with JavaScript code in "content" section. The code will get executed on visiting the newly created page.

# XSS
* Go to "Create" section of Admin panel
* Copy and paste the below code in "content" section and create a page.
```javascript
<script>alert('This text will be shown')</script>
```
* Visit the newly created page

![](https://i.imgur.com/wmx9Xb3.png)

**Comment by shoaiyb** [comment]
This seems like self attacking.
The `content` field is for writing HTML markup or whatever it is I suppose.

The thing to worry about here is the javascript getting executed in the admin panel, which normally doesn't with the latest version.
